### ISSUE TITLE
user-agent

### ISSUE THREAD

**Issue by mynameisquxiangyu** [gys619/jdd#16]
jd_beauty.js
请求头user-agent 
为什么不用$.isNode() ? (process.env.JD_USER_AGENT ? process.env.JD_USER_AGENT : (require('./USER_AGENTS').USER_AGENT)) : ($.getdata('JDUA') ? $.getdata('JDUA') : "jdapp;iPhone;10.0.2;14.3;network/4g;Mozilla/5.0 (iPhone; CPU iPhone OS 14_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148;supportJDSHWK/1") 判断，而是写死的 JD4iPhone/167490 (iPhone; iOS 14.2; Scale/3.00) 
执行->提示：请尝试换服务器ip或者设置"xinruimz-isv.isvjcloud.com"域名直连，或者自定义UA再次尝试(环境变量JD_USER_AGENT) 

jd_beauty_ex.js

**Comment by gys619** [comment]
加一下变量试试

**Comment by mynameisquxiangyu** [comment]
加变量也试了，刚加上可以，过一天又不行了，需要一天换一个，就我一个人这样吗   o(╥﹏╥)o
