### ISSUE TITLE
双十一 荭苞报错是啥子问题？

### ISSUE THREAD

**Issue by mxzsw123456** [gys619/jdd#8]
![1](https://user-images.githubusercontent.com/47170569/139519780-d6e64f20-d97c-4853-a4ab-c4da499c5296.png)

如图，运行显示黑号不过app都能正常领，大佬麻烦看看是我哪里设置的不对吗？

**Comment by gys619** [comment]
自己再config里加export FLCODE='',都是他们的返利链接而已

**Comment by gys619** [comment]
刚加了gua佬的双十一红包脚本，更新一下仓库，跑那个吧gua_1111RedEnvelope.js

**Comment by gys619** [comment]
刚加了gua佬的双十一红包脚本，更新一下仓库，跑那个吧gua_1111RedEnvelope.js

**Comment by mxzsw123456** [comment]
> 刚加了gua佬的双十一红包脚本，更新一下仓库，跑那个吧gua_1111RedEnvelope.js

好的呢我试试，大佬有tg群吗方便交流下

**Comment by mxzsw123456** [comment]
> 刚加了gua佬的双十一红包脚本，更新一下仓库，跑那个吧gua_1111RedEnvelope.js

**Comment by gys619** [comment]
没得tg群

**Comment by mxzsw123456** [comment]
> 没得TG群

哈哈，企鹅和薇芯也行啊!

**Comment by gys619** [comment]
都没得建群，哈哈哈哈哈
